#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# write-extras-build-info.sh - Write BUILD.TXT into extras-toolset root
# ============================================================================
# Generates out/extras-toolset/BUILD.TXT with:
#   - Build timestamp (UTC, used as a human-readable "build number")
#   - Git rev + dirty flag (from the host repo this runs in)
#   - SHA256 of every binary that ships in bin/
#   - List of applied patches per upstream component
#
# Why: user installs extras zips on Win98 by hand and reasonably wants to know
# which build they're looking at without running `dir /od` or comparing zip
# SHAs.  `type BUILD.TXT` from command.com gives them everything they need to
# match what's installed to what's on the maintainer's machine.
#
# Runs LATE in EXTRAS_STEPS -- after every binary is built and installed,
# before package-extras-toolset zips it up.  Idempotent via mark_done; if you
# need a fresh BUILD.TXT (e.g. you re-ran a build step manually), nuke the
# sentinel and re-invoke.
# ============================================================================

source "$(cd "$(dirname "$0")" && pwd)/lib/common.sh"

REPO_ROOT="$ROOT_DIR"
TOOLSET_DIR="$REPO_ROOT/out/extras-toolset"
BUILD_TXT="$TOOLSET_DIR/BUILD.TXT"
PATCHES_DIR="$REPO_ROOT/patches"

require_dir "$TOOLSET_DIR/bin" "Extras toolset not found; build it first"

log "writing $BUILD_TXT"

# UTC ISO timestamp (the de facto "build number" -- monotonic, no ambiguity).
BUILD_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Git info: we run in the toolchain-builder container where /work bind-mounts
# only repro/ (the .git directory lives in the parent on the host).  The
# orchestrator (build.sh) MAY pass git info via env vars BUILD_GIT_REV /
# BUILD_GIT_REV_FULL / BUILD_GIT_DIRTY.  Best-effort; fall back to "unknown".
GIT_REV="${BUILD_GIT_REV:-unknown}"
GIT_REV_FULL="${BUILD_GIT_REV_FULL:-unknown}"
GIT_DIRTY="${BUILD_GIT_DIRTY:-}"

{
    echo "gcc-for-Windows98 extras toolset"
    echo "================================="
    echo ""
    echo "Build timestamp (UTC):  $BUILD_TS"
    echo "Git rev:                ${GIT_REV}${GIT_DIRTY}"
    echo "Git rev (full):         $GIT_REV_FULL"
    echo "Target triple:          ${TARGET:-i686-w64-mingw32}"
    echo ""
    echo "Binary SHA-256 (sha256sum bin/*.exe bin/*.dll):"
    echo "-----------------------------------------------"
    (
        cd "$TOOLSET_DIR/bin"
        # Sort for stable ordering across runs.
        ls *.exe *.dll 2>/dev/null | sort -u | while read -r f; do
            sha="$(sha256sum "$f" | cut -d' ' -f1)"
            printf "%-32s %s\n" "$f" "$sha"
        done
    )
    echo ""
    echo "Applied patches by component:"
    echo "-----------------------------"
    if [[ -d "$PATCHES_DIR" ]]; then
        for comp_dir in "$PATCHES_DIR"/*/; do
            [[ -d "$comp_dir" ]] || continue
            comp="$(basename "$comp_dir")"
            for ver_dir in "$comp_dir"*/; do
                [[ -d "$ver_dir" ]] || continue
                ver="$(basename "$ver_dir")"
                series="$ver_dir/series.txt"
                if [[ -f "$series" ]]; then
                    echo ""
                    echo "  $comp ($ver):"
                    grep -v '^\s*#' "$series" | grep -v '^\s*$' | sed 's/^/    /'
                fi
            done
        done
    fi
    echo ""
    echo "(File generated by repro/scripts/write-extras-build-info.sh)"
} > "$BUILD_TXT"

log "wrote $(wc -l < "$BUILD_TXT") lines to BUILD.TXT"
mark_done write-extras-build-info
